<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <!-- NuGet Package -->
  <PropertyGroup>
    <PackageId>AzureFunctions.DisabledWhen.SourceGenerator</PackageId>
    <Description>Conditionally disable Azure Functions based on configuration values using attributes and source generation.</Description>
    <PackageTags>Azure;Functions;Disable</PackageTags>
  </PropertyGroup>

  <!-- Analyzer packaging -->
  <PropertyGroup>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IncludeSymbols>false</IncludeSymbols>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddPackageFiles</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
</Project>
