<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AzureFunctions.DisabledWhen.Core\AzureFunctions.DisabledWhen.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="2.0.0" />
  </ItemGroup>

</Project>
