<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <!-- NuGet Package -->
  <PropertyGroup>
    <PackageId>AzureFunctions.DisabledWhen.Reflection</PackageId>
    <VersionPrefix>1.0.0</VersionPrefix>
	<VersionSuffix>alpha</VersionSuffix>
    <Description>Conditionally disable Azure Functions based on configuration values using attributes.</Description>
    <PackageTags>Azure;Functions;Disable</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
</Project>
