<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <!-- NuGet Package -->
  <PropertyGroup>
    <PackageId>AzureFunctions.DisabledWhen</PackageId>
    <Description>Conditionally disable Azure Functions based on configuration values using attributes.</Description>
    <PackageTags>Azure;Functions;Disable</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
