using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace AzureFunctions.DisabledWhen.SourceGenerator.Internal;

internal static class Emitter
{
    public static SourceText GenerateRegistry(
        ImmutableArray<FunctionDisableInfo> functions,
        ImmutableArray<InterceptorInfo> interceptors)
    {
        var conditionsEntries = GenerateConditionsEntries(functions);
        var interceptorMethods = GenerateInterceptorMethods(interceptors);

        var source = $$"""
            // <auto-generated />
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Collections.Immutable;
            using System.Linq;
            using System.Threading.Tasks;
            using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.Hosting;
            using Microsoft.Extensions.Logging;

            namespace System.Runtime.CompilerServices
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }

            namespace AzureFunctions.DisabledWhen
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
                file readonly struct DisabledCondition
                {
                    public DisabledCondition(string configKey, string? configValue, global::System.StringComparison comparer, bool matchNullOrEmpty = false)
                    {
                        ConfigKey = configKey;
                        ConfigValue = configValue;
                        ConfigValueComparer = comparer;
                        MatchNullOrEmpty = matchNullOrEmpty;
                    }

                    public string ConfigKey { get; }
                    public string? ConfigValue { get; }
                    public global::System.StringComparison ConfigValueComparer { get; }
                    public bool MatchNullOrEmpty { get; }
                }

                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
                file static class DisabledWhenRegistry
                {
                    private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<DisabledCondition>> Conditions =
                        new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<DisabledCondition>>(global::System.StringComparer.Ordinal)
                        {
            {{conditionsEntries}}
                        };

                    public static bool TryGetConditions(string entryPoint, out global::System.Collections.Generic.IReadOnlyList<DisabledCondition>? conditions)
                    {
                        if (Conditions.TryGetValue(entryPoint, out var list))
                        {
                            conditions = list;
                            return true;
                        }
                        conditions = null;
                        return false;
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
                file sealed class GeneratedDisabledWhenMetadataProvider : IFunctionMetadataProvider
                {
                    private readonly IServiceProvider serviceProvider;
                    private readonly IConfiguration configuration;
                    private readonly ILogger<GeneratedDisabledWhenMetadataProvider>? logger;

                    public GeneratedDisabledWhenMetadataProvider(
                        IServiceProvider serviceProvider,
                        IConfiguration configuration,
                        ILogger<GeneratedDisabledWhenMetadataProvider>? logger = null)
                    {
                        this.serviceProvider = serviceProvider;
                        this.configuration = configuration;
                        this.logger = logger;
                    }

                    public async Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                    {
                        var functionMetadataProvider = this.serviceProvider
                            .GetServices<IFunctionMetadataProvider>()
                            .Last(x => x.GetType() != typeof(GeneratedDisabledWhenMetadataProvider));

                        var metaData = await functionMetadataProvider
                            .GetFunctionMetadataAsync(directory)
                            .ConfigureAwait(false);

                        var disabledFunctions = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);

                        foreach (var function in metaData)
                        {
                            if (function.EntryPoint is null || function.Name is null)
                            {
                                continue;
                            }

                            if (!DisabledWhenRegistry.TryGetConditions(function.EntryPoint, out var conditions) || conditions is null)
                            {
                                continue;
                            }

                            foreach (var condition in conditions)
                            {
                                var configValue = configuration.GetValue<string>(condition.ConfigKey);
                                var isMatch = condition.MatchNullOrEmpty
                                    ? string.IsNullOrEmpty(configValue)
                                    : string.Equals(configValue, condition.ConfigValue, condition.ConfigValueComparer);

                                if (isMatch)
                                {
                                    logger?.LogWarning("Function {FunctionName} is disabled", function.Name);
                                    disabledFunctions.Add(function.EntryPoint);
                                    break;
                                }
                            }
                        }

                        return [.. metaData.Where(m => !disabledFunctions.Contains(m.EntryPoint!))];
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
                file static class UseDisabledWhenInterceptor
                {
            {{interceptorMethods}}
                    private static IHostBuilder UseDisabledWhenGenerated(this IHostBuilder builder)
                        => builder.ConfigureServices(services => services.AddSingleton<IFunctionMetadataProvider, GeneratedDisabledWhenMetadataProvider>());
                }
            }
            """;

        return SourceText.From(source, Encoding.UTF8);
    }

    private static string GenerateInterceptorMethods(ImmutableArray<InterceptorInfo> interceptors)
    {
        if (interceptors.IsEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        var index = 0;

        foreach (var interceptor in interceptors.Distinct())
        {
            sb.AppendLine($$"""
                        [global::System.Runtime.CompilerServices.InterceptsLocation({{interceptor.Version}}, "{{interceptor.Data}}")]
                        public static IHostBuilder UseDisabledWhen_{{index}}(this IHostBuilder builder)
                            => builder.UseDisabledWhenGenerated();

            """);
            index++;
        }

        return sb.ToString().TrimEnd();
    }

    private static string GenerateConditionsEntries(ImmutableArray<FunctionDisableInfo> functions)
    {
        var grouped = functions
            .GroupBy(f => f.EntryPoint)
            .ToDictionary(
                g => g.Key,
                g => g.SelectMany(f => f.Conditions).Distinct().ToList());

        if (grouped.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        foreach (var kvp in grouped)
        {
            var conditions = string.Join(",\n                    ",
                kvp.Value.Select(c =>
                {
                    var configValue = c.ConfigValue is null ? "null" : $"\"{EscapeString(c.ConfigValue)}\"";
                    var comparer = GetStringComparisonName(c.ConfigValueComparer);
                    var matchNullOrEmpty = c.MatchNullOrEmpty ? "true" : "false";
                    return $"new DisabledCondition(\"{EscapeString(c.ConfigKey)}\", {configValue}, global::System.StringComparison.{comparer}, {matchNullOrEmpty})";
                }));

            sb.AppendLine($$"""
                        ["{{EscapeString(kvp.Key)}}"] = new global::System.Collections.Generic.List<DisabledCondition>
                        {
                            {{conditions}},
                        },
            """);
        }

        return sb.ToString().TrimEnd();
    }

    private static string EscapeString(string value) =>
        value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");

    private static string GetStringComparisonName(StringComparison comparison) =>
        comparison switch
        {
            StringComparison.CurrentCulture => "CurrentCulture",
            StringComparison.CurrentCultureIgnoreCase => "CurrentCultureIgnoreCase",
            StringComparison.InvariantCulture => "InvariantCulture",
            StringComparison.InvariantCultureIgnoreCase => "InvariantCultureIgnoreCase",
            StringComparison.Ordinal => "Ordinal",
            StringComparison.OrdinalIgnoreCase => "OrdinalIgnoreCase",
            _ => "Ordinal"
        };
}
