using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace AzureFunctions.DisabledWhen.SourceGenerator.Internal;

internal static class Emitter
{
    public static SourceText GenerateRegistry(ImmutableArray<FunctionDisableInfo> functions)
    {
        var conditionsEntries = GenerateConditionsEntries(functions);

        var source = $$"""
            // <auto-generated />
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Collections.Immutable;
            using System.Linq;
            using System.Threading.Tasks;
            using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
            using Microsoft.Extensions.Configuration;
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.Hosting;
            using Microsoft.Extensions.Logging;

            namespace AzureFunctions.DisabledWhen;

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
            internal readonly struct DisabledCondition
            {
                public DisabledCondition(string configKey, string? configValue, global::System.StringComparison comparer, bool matchNullOrEmpty = false)
                {
                    ConfigKey = configKey;
                    ConfigValue = configValue;
                    ConfigValueComparer = comparer;
                    MatchNullOrEmpty = matchNullOrEmpty;
                }

                public string ConfigKey { get; }
                public string? ConfigValue { get; }
                public global::System.StringComparison ConfigValueComparer { get; }
                public bool MatchNullOrEmpty { get; }
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal static class DisabledWhenRegistry
            {
                private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<DisabledCondition>> Conditions =
                    new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<DisabledCondition>>(global::System.StringComparer.Ordinal)
                    {
            {{conditionsEntries}}
                    };

                public static bool TryGetConditions(string entryPoint, out global::System.Collections.Generic.IReadOnlyList<DisabledCondition>? conditions)
                {
                    if (Conditions.TryGetValue(entryPoint, out var list))
                    {
                        conditions = list;
                        return true;
                    }
                    conditions = null;
                    return false;
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
            internal sealed class DisabledWhenMetadataProvider : IFunctionMetadataProvider
            {
                private readonly IServiceProvider _serviceProvider;
                private readonly IConfiguration _configuration;
                private readonly ILogger<DisabledWhenMetadataProvider>? _logger;

                public DisabledWhenMetadataProvider(
                    IServiceProvider serviceProvider,
                    IConfiguration configuration,
                    ILogger<DisabledWhenMetadataProvider>? logger = null)
                {
                    _serviceProvider = serviceProvider;
                    _configuration = configuration;
                    _logger = logger;
                }

                public async Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                {
                    var functionMetadataProvider = _serviceProvider
                        .GetServices<IFunctionMetadataProvider>()
                        .Last(x => x.GetType() != typeof(DisabledWhenMetadataProvider));

                    var metaData = await functionMetadataProvider
                        .GetFunctionMetadataAsync(directory)
                        .ConfigureAwait(false);

                    var disabledFunctions = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);

                    foreach (var function in metaData)
                    {
                        if (function.EntryPoint is null || function.Name is null)
                            continue;

                        if (!DisabledWhenRegistry.TryGetConditions(function.EntryPoint, out var conditions) || conditions is null)
                            continue;

                        foreach (var condition in conditions)
                        {
                            var configValue = _configuration.GetValue<string>(condition.ConfigKey);
                            var isMatch = condition.MatchNullOrEmpty
                                ? string.IsNullOrEmpty(configValue)
                                : string.Equals(configValue, condition.ConfigValue, condition.ConfigValueComparer);

                            if (isMatch)
                            {
                                LogFunctionDisabled(function.Name);
                                disabledFunctions.Add(function.EntryPoint);
                                break;
                            }
                        }
                    }

                    return metaData.Where(m => m.EntryPoint is null || !disabledFunctions.Contains(m.EntryPoint)).ToImmutableArray();
                }

                private void LogFunctionDisabled(string functionName)
                {
                    _logger?.LogWarning("Function {FunctionName} is disabled", functionName);
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AzureFunctions.DisabledWhen.SourceGenerator", "1.0.0")]
            public static class IHostBuilderExtensions
            {
                public static IHostBuilder UseDisabledWhen(this IHostBuilder builder)
                    => builder.ConfigureServices(services => services.AddSingleton<IFunctionMetadataProvider, DisabledWhenMetadataProvider>());
            }
            """;

        return SourceText.From(source, Encoding.UTF8);
    }

    private static string GenerateConditionsEntries(ImmutableArray<FunctionDisableInfo> functions)
    {
        var grouped = functions
            .GroupBy(f => f.EntryPoint)
            .ToDictionary(
                g => g.Key,
                g => g.SelectMany(f => f.Conditions).Distinct().ToList());

        if (grouped.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        foreach (var kvp in grouped)
        {
            var conditions = string.Join(",\n                    ",
                kvp.Value.Select(c =>
                {
                    var configValue = c.ConfigValue is null ? "null" : $"\"{EscapeString(c.ConfigValue)}\"";
                    var comparer = GetStringComparisonName(c.ConfigValueComparer);
                    var matchNullOrEmpty = c.MatchNullOrEmpty ? "true" : "false";
                    return $"new DisabledCondition(\"{EscapeString(c.ConfigKey)}\", {configValue}, global::System.StringComparison.{comparer}, {matchNullOrEmpty})";
                }));

            sb.AppendLine($$"""
                        ["{{EscapeString(kvp.Key)}}"] = new global::System.Collections.Generic.List<DisabledCondition>
                        {
                            {{conditions}},
                        },
            """);
        }

        return sb.ToString().TrimEnd();
    }

    private static string EscapeString(string value) =>
        value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");

    private static string GetStringComparisonName(StringComparison comparison) =>
        comparison switch
        {
            StringComparison.CurrentCulture => "CurrentCulture",
            StringComparison.CurrentCultureIgnoreCase => "CurrentCultureIgnoreCase",
            StringComparison.InvariantCulture => "InvariantCulture",
            StringComparison.InvariantCultureIgnoreCase => "InvariantCultureIgnoreCase",
            StringComparison.Ordinal => "Ordinal",
            StringComparison.OrdinalIgnoreCase => "OrdinalIgnoreCase",
            _ => "Ordinal"
        };
}
